name: Destroy
on:
  workflow_dispatch:
    inputs:
      default_region:
        description: 'AMI default region'
        required: true
        default: 'us-west-2'
      s3_key:
        description: 'S3 Key'
        required: true
        default: 'tfstate/terraform.tfstate'
      s3_region:
        description: 'S3 region'
        required: true
        default: 'us-west-2'
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.default_region }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.6

      - name: Destroy EC2 by Terraform
        working-directory: terraform
        id: destroy_terraform
        run: |
          terraform init -backend-config='bucket=${{ secrets.S3_BUCKET_NAME }}' \
          -backend-config='key=${{ github.event.inputs.s3_key }}' \
          -backend-config='region=${{ github.event.inputs.s3_region }}'
          terraform destroy -var='ingress_ip=${{ secrets.Local_IP_Address }}' -auto-approve